[package]
name = "selium-std"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
brotli2 = "0.3"
bytes = "1.4"
flate2 = { version = "1.0", features = ["zlib"] }
lz4_flex = "0.11.1"
selium-traits = { version = "0.1", path = "../traits" }
zstd = "0.12"

[dev-dependencies]
criterion = "0.5"
fake = "2.8"

[[bench]]
name = "compression"
harness = false
