[package]
name = "selium-switchboard"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
futures = { workspace = true, features = ["alloc", "std"] }
pin-project = { workspace = true }
selium-switchboard-protocol = { path = "../protocol" }
selium-userland = { path = "../../../system/userland" }
thiserror = { workspace = true, features = ["std"] }
tracing = { workspace = true }

[dev-dependencies]
selium-switchboard-core = { path = "../core" }
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
