[workspace]
members = ["client", "server", "common", "tests", "benchmarks"]
default-members = ["client", "server", "common", "tests"]

[workspace.package]
edition = "2021"
authors = ["Selium Contributors"]
license = "MPL-2.0"
homepage = "https://selium.com"
repository = "https://github.com/seliumlabs/selium"
readme = "README.md"
keywords = [
    "selium",
    "broker",
    "messaging",
    "message",
    "streaming",
    "stream",
    "queue",
    "rpc",
]
categories = ["network-programming", "webassembly"]
