[package]
name = "selium-atlas"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
futures = { workspace = true, features = ["alloc", "std"] }
selium-atlas-protocol = { path = "../protocol" }
selium-switchboard = { path = "../../switchboard/client", optional = true }
selium-userland = { path = "../../../system/userland" }
thiserror = { workspace = true, features = ["std"] }
tracing = { workspace = true }

[features]
default = ["switchboard"]
switchboard = ["dep:selium-switchboard"]
