name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  check:
    name: Cargo checks
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: mozilla-actions/sccache-action@v0.0.9

      - name: cargo check
        run: cargo check --workspace --all-targets

      - name: cargo fmt
        run: cargo fmt --all --check

      - name: cargo clippy
        run: cargo clippy -- -D warnings

  test:
    name: Cargo tests
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@v0.0.9

      - name: cargo test
        run: cargo test --workspace --all-targets

  ignored:
    name: Cargo ignored tests
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: mozilla-actions/sccache-action@v0.0.9

      - name: cargo test --ignored
        run: cargo test -- --ignored

  loom:
    name: Loom tests
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@v0.0.9

      - name: selium-messaging loom tests
        run: cargo test -p selium-messaging --features loom --tests
